function [fitresult, gof] = createFitLin(xi, yi)
%CREATEFIT1(XI,YI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xi
%      Y Output: yi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jun-2014 12:52:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xi, yi );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf];
%opts.Robust = 'Bisquare';
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'yi vs. xi', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'xi' );
% ylabel( 'yi' );
% grid on


