function [fitresult, gof] = createFitFourier2(msr)
%CREATEFIT1(MSR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: msr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Jul-2014 15:38:19


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], msr );

% Set up fittype and options.
ft = fittype( 'fourier2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf -Inf -Inf];
opts.StartPoint = [0 0 0 0 0 0.0628318530717959];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'msr', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel( 'msr' );
% grid on


